spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 123456



#    url: jdbc:mysql://129.28.75.111:23333/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    url: jdbc:mysql://172.27.0.4:23333/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 1234567890
  jpa:
    database: MYSQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: GMT+8
    hibernate:
      ddl-auto: update



#           docker volume create flyVolume
#           docker run --rm -d -e MYSQL_ROOT_PASSWORD=1234567890 -v flyVolume:/var/lib/mysql -p 23333:3306 mysql:5.7.27
#
#