spring:
  datasource:
    url: jdbc:mysql://localhost:23333/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: GMT+8
    hibernate:
      ddl-auto: update
logging:
  file: ./debug.log
