spring:
  application:
    name: wechat
  profiles:
    #    active: tencent-cloud
    active: local
  #    keytool -genkeypair -alias tomcat -dname "CN=fly,OU=fly,O=fly,L=fly,ST=KunMing,C=CN" -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
  #    username: root
  #    password: 123456
  ##    url: jdbc:mysql://localhost:23333/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
  ##    username: root
  ##    password: 1234567890
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jpa:
  #    database: MYSQL
  #    show-sql: false
  #    open-in-view: false
  #    properties:
  #      hibernate.jdbc.time_zone: GMT+8
  #    hibernate:
  #      ddl-auto: update
  #      naming:
  #        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: ALWAYS
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8087
  ssl:
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
    keyAlias: tomcat
    enabled: true
    key-store-password: 1234567890

wechat:
  app-id: wxa5d31b433dfe9c5f
  app-secret: b2947f3f2fac67ef335cab65b6cdac2d
  mch-id: 111111
  mch-key: xxxxxx
  notify-url: http://www.example.com/wx/order/pay-notify
  # 商户证书文件路径
  # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
  key-path: xxxxx
  map-key: U3HBZ-AK6HR-4JOWL-WRAYT-AJ7VS-MQFSJ
guava:
  cache:
    config:
      expire-after-access-duration=1000